name: sophiread
channels:
  - conda-forge
dependencies:
  - cmake
  - ninja
  - clang-format
  - hdf5
  # - gmock
  # - qt
  - gtest
  # - qwt
  - eigen
  - tbb-devel
  - spdlog
  #- mlpack
  - cereal
  - armadillo
  - ensmallen

  # Not Windows, OpenGL implementation:
  # - mesalib>=18.0.0
  # - mesa-libgl-devel-cos7-x86_64>=18.3.4
  # - mesa-libgl-cos7-x86_64>=18.3.4

  # documentation
  - doxygen
  - graphviz
